### ISSUE TITLE
 `write` Method Appends Instead of Overwriting Configuration File

### ISSUE THREAD

**Issue by brianzhouzc** [Preocts/commented-configparser#46]
### **Description:**

When using the write method to save a configuration file, the content is appended instead of overwriting the existing content. This behavior occurs even when opening the file in 'w' (write) mode.

### **Steps to Reproduce:**

1.  Create a configuration file named test.ini with the following content:
```
[section]
test = 1
```
2. Use the following script to update the configuration file:
```
from time import sleep
from commentedconfigparser import CommentedConfigParser

config = CommentedConfigParser()
config.read('test.ini')

i = 0
while i < 10:
    config.set('section', 'test', str(i))
    with open('test.ini', 'w') as config_file:
        config.write(config_file)
    i += 1
    sleep(1)
```

### **Expected Behavior:**
The test.ini file should be overwritten with the following content:
```
[section]
test = 9
```

### **Actual Behavior:**
The test.ini file is appended multiple times, resulting in:
```
[section]
test = 0

[section]
test = 1

[section]
test = 2

[section]
test = 3

...
```

**Comment by Preocts** [comment]
Yup, looks like a mutable isn't being cleared when it should and it is just collecting all the set sections.

Hopefully I'll have some free-time in next week or two. I've been meaning to implement some suggestions on how the internals could be structured.

**Comment by Preocts** [comment]
Thanks for calling this out!
